// app/layout.tsx
import { Box, Flex } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ApolloChakraProvider from './ApolloChakraProvider';
import Sidebar from './components/Sidebar';
import { SessionProvider } from 'next-auth/react';
import Header from './components/header';
import NextAuthProvider from '@/src/providers/NextAuth';
import { MobileMenu } from './components/layout/MobileMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <NextAuthProvider>
          <ApolloChakraProvider>
            <SessionProvider>
              <Flex
                h="100vh"
                w="100%"
                bgColor="orange.100"
                alignItems="stretch"
                gap={4} // コンポーネント間の間隔を設定
                p={{ base: 2, md: 4 }}
              >
                {/* サイドバー - モバイルでは非表示 */}
                <Box
                  display={{ base: 'none', md: 'block' }}
                  flexShrink={0} // サイドバーのサイズを固定
                >
                  <Sidebar />
                </Box>

                {/* メインコンテンツエリア */}
                <Flex
                  flexDirection="column"
                  flex={1} // flexGrow を flex に変更
                  gap={4} // 内部の要素間の間隔を設定
                  minW={0} // オーバーフローを防ぐ
                >
                  {/* ヘッダー */}
                  <Box
                    h={{ base: '50px', md: '60px' }}
                    bgColor="orange.50"
                    borderRadius={10}
                    display="flex"
                    alignItems="center"
                    px={4} // paddingを左右のみに
                    justifyContent="space-between"
                  >
                    <MobileMenu />
                    <Header />
                  </Box>

                  {/* コンテンツ */}
                  <Box
                    flex={1} // flexGrow を flex に変更
                    bgColor="orange.50"
                    borderRadius={10}
                    p={4}
                    overflowY="auto"
                    minH={0} // スクロールを適切に機能させる
                  >
                    {children}
                  </Box>
                </Flex>
              </Flex>
            </SessionProvider>
          </ApolloChakraProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
