import { Box, HStack, VStack } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ApolloChakraProvider from "./ApolloChakraProvider";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={inter.className}>
				<ApolloChakraProvider>
					<HStack
						h="100vh"
						w="100%"
						alignItems="stretch"
						bgColor="orange.100"
						p={4}
					>
						<Sidebar />
						<VStack flexGrow={1} spacing={0}>
							<Box h="60px" w="100%" bgColor="orange.50" borderTopRadius={10}>
								<h1>ヘッダー</h1>
							</Box>
							<Box
								flexGrow={1}
								w="100%"
								bgColor="orange.50"
								borderBottomRadius={10}
							>
								{children}
							</Box>
						</VStack>
					</HStack>
				</ApolloChakraProvider>
			</body>
		</html>
	);
}
