import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ApolloChakraProvider from "./ApolloChakraProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={inter.className}>
				<ApolloChakraProvider>{children}</ApolloChakraProvider>
			</body>
		</html>
	);
}
